"""удалил за ненадобностью табличку vacancy_skills

Revision ID: ee6fd7f01367
Revises: e03daec06e5d
Create Date: 2026-05-25 19:25:13.101620

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee6fd7f01367'
down_revision: Union[str, Sequence[str], None] = 'e03daec06e5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vacancy_skills')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vacancy_skills',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('vacancy_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('skill_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['vacancy_id'], ['vacancies.id'], name=op.f('vacancy_skills_vacancy_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('vacancy_skills_pkey'))
    )
    # ### end Alembic commands ###
